# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/ying-zhang
  RSS: /atom.xml

# Content
excerpt_link: 阅读全文...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.ico
